CREATE TABLE CLIENT (
    IDCLIENT INT AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    MAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(16) NOT NULL
);


CREATE TABLE ACCOUNT (
    IDACCOUNT INT AUTO_INCREMENT  PRIMARY KEY,
    NUMBERACCOUNT INT NOT NULL,
	TYPEACCOUNT VARCHAR(2) NOT NULL,
    ACCOUNTBALANCE DECIMAL NOT NULL,
    IDCLIENT INT NOT NULL,
    FOREIGN KEY(IDCLIENT) REFERENCES CLIENT(IDCLIENT) 
);

CREATE TABLE TRANSACTIONS (
	IDTRANSACTION INT AUTO_INCREMENT  PRIMARY KEY,
	DESCRIBLE VARCHAR(10) NOT NULL,
	VALUETRANSACTION DECIMAL NOT NULL, 
	DATETRANSACTION DATETIME,
	IDACCOUNT INT NOT NULL,
	FOREIGN KEY (IDACCOUNT) REFERENCES ACCOUNT(IDACCOUNT)
)